FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install python3.11 python3.11-venv 

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /home/user/SD_DB/Stare_Dori_DB
WORKDIR /home/user/SD_DB/Stare_Dori_DB

ENTRYPOINT ["./start.sh"]
